version: '3.8'

services:

  web:
    build: ./project
    command: uvicorn app.main:app --reload --workers 1 --host 0.0.0.0 --port 8000
    volumes:
      - ./project:/usr/src/app
    ports:
      - 8004:8000
    environment:
      - DATABASE_URL=postgresql+asyncpg://postgres:postgres@db:5445/foo
    depends_on:
      - db
      - redis
  
  redis:
    image: redis:6.2-alpine
    ports:
      - 6379:6379
    command: redis-server --save 60 1 --requirepass 123456 --loglevel warning
    volumes:
      - redis_data:/data

  db:
    image: postgres:12-alpine
    ports:
      - 5445:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=foo
    volumes:
      - postgres_data:/var/lib/postgresql/data


volumes:
  postgres_data: {}
  redis_data: {}
