"""userbook

Revision ID: 589453377d21
Revises: 5926afb5aed2
Create Date: 2024-05-16 14:20:35.661392

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel            


# revision identifiers, used by Alembic.
revision = '589453377d21'
down_revision = '5926afb5aed2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_book',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('book_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['book_id'], ['book.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'book_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_book')
    # ### end Alembic commands ###